# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=1)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=b'assessment/questions/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Assessment_question')),
            ],
            options={
                'db_table': 'assessment_images',
            },
        ),
    ]
