# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0002_assessment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_image_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=1)),
                ('item_no', models.IntegerField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'assessment_image_answers',
            },
        ),
        migrations.AddField(
            model_name='assessment_question',
            name='uploaded_question',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='assessment_image_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Assessment_question'),
        ),
    ]
