# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 02:06
from __future__ import unicode_literals

from django.db import migrations
from ..forms.user_type import *

def add_user_types(apps,schema_editor):
	user_types = ['Senior Consultant','Manager','Junior Consultant']

	for user_type in user_types:
		row = {}
		row['name'] = user_type
		row['is_active'] = True
		user_type_form = User_type_form(row)

		if user_type_form.is_valid():
			user_type_form.save()

class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0002_auto_20171025_0958'),
    ]

    operations = [
    	migrations.RunPython(add_user_types)
    ]
