# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-02 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0002_user_credit_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_credit',
            name='session_credits_left',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
