# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0003_auto_20171219_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_image',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
        migrations.AddField(
            model_name='assessment_image_answer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
    ]
