# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0003_auto_20171025_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment_recommendation',
            name='question',
        ),
    ]
