# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-09 07:28
from __future__ import unicode_literals

from django.db import migrations
import time

def fix_deleted_user(apps,schema_editor):
	Users = apps.get_model("systech_account", "User")

	users = Users.objects.all()

	for user in users:
		if not user.is_active:
			user.email += ("__"+str(time.time()))
			user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0004_user_credit_enrollment_code'),
    ]

    operations = [
    	migrations.RunPython(fix_deleted_user)
    ]
