# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0004_auto_20171219_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_upload_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=1)),
                ('item_no', models.IntegerField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
                ('is_deleted', models.BooleanField(default=0)),
                ('company_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company_assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Assessment_question')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Transaction_type')),
            ],
            options={
                'db_table': 'assessment_upload_answers',
            },
        ),
        migrations.AddField(
            model_name='assessment_answer',
            name='uploaded_question',
            field=models.BooleanField(default=0),
        ),
    ]
