# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0004_remove_assessment_recommendation_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_assessment',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
