# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-02 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0005_auto_20171229_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_score',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Assessment_question'),
        ),
    ]
