# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0005_company_assessment_consultant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_question',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
