# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-02 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0006_assessment_score_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_score',
            name='uploaded_question',
            field=models.BooleanField(default=0),
        ),
    ]
