# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0006_auto_20171026_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_finding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('is_import', models.BooleanField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Assessment_question')),
            ],
            options={
                'db_table': 'assessment_findings',
            },
        ),
    ]
