# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-28 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0007_gradelevel_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradelevel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
        migrations.AddField(
            model_name='school',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
    ]
