# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0007_assessment_finding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment_answer',
            name='choice',
        ),
        migrations.AddField(
            model_name='assessment_question',
            name='has_multiple_choice',
            field=models.BooleanField(default=0),
        ),
    ]
