# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0008_auto_20180110_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Math_symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company')),
            ],
            options={
                'db_table': 'math_symbols',
            },
        ),
    ]
