# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 02:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0008_auto_20171026_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_answer',
            name='choice',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name=b'Choice'), blank=True, null=True, size=None),
        ),
    ]
