# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0009_assessment_answer_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='transaction_type',
        ),
    ]
