# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-29 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0009_auto_20181128_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_rename',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
