# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0009_math_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='math_symbol',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
