# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0010_math_symbol_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='math_symbol',
            name='above_text',
            field=models.BooleanField(default=0),
        ),
    ]
