# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-24 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0011_math_symbol_above_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='math_symbol',
            name='syntax',
            field=models.TextField(blank=True, null=True),
        ),
    ]
