# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 03:39
from __future__ import unicode_literals

from django.db import migrations
from ..views.common import *

def transfer_accounts(apps,schema_editor):
	User = apps.get_model("systech_account","User")
	Company = apps.get_model("systech_account","Company")
	Assessment_image_answer = apps.get_model("systech_account","Assessment_image_answer")
	Assessment_image = apps.get_model("systech_account","Assessment_image")
	Assessment_question = apps.get_model("systech_account","Assessment_question")
	Transaction_type = apps.get_model("systech_account","Transaction_type")

	users = User.objects.all()
	company_details = Company.objects.get(id=2)
	for user in users:
		if user.pk == 130 or user.pk == 131 or user.pk == 132 or user.pk == 133:
			user.company = company_details
			user.save() 

	image_answers = Assessment_image_answer.objects.all()
	for image_answer in image_answers:
		if image_answer.company.pk == 3 or image_answer.company.pk == 4 or image_answer.company.pk == 5 or image_answer.company.pk == 6:
			image_answer.company = company_details
			image_answer.save()

	images = Assessment_image.objects.all()
	for image in images:
		if image.company.pk == 3 or image.company.pk == 4 or image.company.pk == 5 or image.company.pk == 6:
			image.company = company_details
			image.save()

	questions = Assessment_question.objects.all()
	for question in questions:
		if question.company.pk == 3 or question.company.pk == 4 or question.company.pk == 5 or question.company.pk == 6:
			question.company = company_details
			question.save()

	transaction_types = Transaction_type.objects.all()
	for transaction_type in transaction_types:
		if transaction_type.company.pk == 3 or transaction_type.company.pk == 4 or transaction_type.company.pk == 5 or transaction_type.company.pk == 6:
			transaction_type.company = company_details
			transaction_type.save()

class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0012_math_symbol_syntax'),
    ]

    operations = [
    	migrations.RunPython(transfer_accounts)
    ]
