# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0012_remove_user_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_assessment',
            name='transaction_type',
        ),
    ]
