# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-12 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0013_auto_20181206_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('score_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'trainer_note',
            },
        ),
    ]
