# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 08:52
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0013_remove_company_assessment_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_assessment',
            name='transaction_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name=b'Transaction_type'), blank=True, null=True, size=None),
        ),
    ]
