# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 02:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0013_auto_20180201_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_assessment',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilitator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company_assessment',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant', to=settings.AUTH_USER_MODEL),
        ),
    ]
