# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0014_company_assessment_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment_question',
            old_name='has_multiple_choice',
            new_name='has_multiple_answer',
        ),
    ]
