# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-07 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0014_auto_20180203_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_type',
            name='is_default',
            field=models.BooleanField(default=0),
        ),
    ]
