# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-02 02:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0015_auto_20171027_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generated_assessment_recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name=b'Assessment_recommendation'), blank=True, null=True, size=None)),
                ('company_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company_assessment')),
            ],
            options={
                'db_table': 'generated_assessment_recommendations',
            },
        ),
    ]
