# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-20 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0015_user_type_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiple_image_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('image_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Assessment_image_answer')),
            ],
            options={
                'db_table': 'multiple_image_answers',
            },
        ),
    ]
