# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 03:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0016_generated_assessment_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_question',
            name='is_general',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='assessment_question',
            name='transaction_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name=b'Transaction_type'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='assessment_question',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Transaction_type'),
        ),
    ]
