# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-20 06:55
from __future__ import unicode_literals

from django.db import migrations
from ..views.common import *
from ..forms.assessments import *

def multiple_image_answers(apps,schema_editor):
	Assessment_image_answer = apps.get_model("systech_account","Assessment_image_answer")
	Multiple_image_answer = apps.get_model("systech_account","Multiple_image_answer")

	assessment_image_answers = Assessment_image_answer.objects.all()
	for image_answer in assessment_image_answers:
		row = {}
		row['name'] = image_answer.answer
		row['image_answer'] = image_answer.pk
		row['is_active'] = image_answer.is_active

		image_form = Multiple_image_answer_form(row)

		if image_form.is_valid():
			image_form.save()
		else:
			raise_error(json.dumps(image_form.errors))

class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0016_multiple_image_answer'),
    ]

    operations = [
    	migrations.RunPython(multiple_image_answers)
    ]
