# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0017_auto_20180220_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_session',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Transaction_type'),
        ),
    ]
