# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0018_assessment_answer_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_assessment',
            name='is_generated',
            field=models.BooleanField(default=0),
        ),
    ]
