# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-08 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0018_assessment_session_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_question',
            name='timer',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
