# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-18 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0018_enrollment_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rfid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
