# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-18 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0019_user_rfid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(blank=True, max_length=20, null=True)),
                ('log_time', models.TimeField(blank=True, default=None, null=True)),
                ('log_date', models.DateField(default=django.utils.timezone.now)),
                ('sync_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_time_logs',
            },
        ),
    ]
