# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-08 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0019_assessment_question_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_session',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Assessment_question'),
        ),
    ]
