# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 01:16
from __future__ import unicode_literals

from django.db import migrations, models
from ..views.common import *

def delete_dbs(apps,schema_editor):
	table_names = [
		'Assessment_question', 
		'Assessment_effect', 
		'Assessment_recommendation', 
		'Assessment_answer', 
		'Assessment_finding', 
		'Generated_assessment_recommendation',
		'Company',
		'Company_assessment',
		'Choice',
		'Transaction_type',
	]

	for table_name in table_names:
		table = str_to_model(table_name).objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0019_company_assessment_is_generated'),
    ]

    operations = [
    	migrations.RunPython(delete_dbs)
    ]
