# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0020_auto_20171114_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
    ]
