# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-02 06:35
from __future__ import unicode_literals

from django.db import migrations
from ..views.common import *

def save_username(apps,schema_editor):
	User = apps.get_model("systech_account","User")

	users = User.objects.filter(is_active=True)
	for user in users:
		get_email = user.email.split("@")
		username = get_email[0]
		user.username = username
		user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0021_user_username'),
    ]

    operations = [
    	migrations.RunPython(save_username)
    ]
