# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0021_user_is_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_related_required',
            field=models.BooleanField(default=0),
        ),
    ]
