# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0022_choice_is_related_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_answer',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Transaction_type'),
        ),
    ]
