# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-21 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0023_questiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.QuestionType'),
        ),
    ]
