# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-16 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0023_assessment_answer_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_question',
            name='has_follow_up',
            field=models.BooleanField(default=0),
        ),
    ]
