# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-03 09:52
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Count, Sum, Avg,Min,Q,F,Func

def delete_data(apps,schema_editor):
	Company_assessment = apps.get_model("systech_account","Company_assessment")
	Assessment_session = apps.get_model("systech_account", "Assessment_session")
	Assessment_upload_answer = apps.get_model("systech_account", "Assessment_upload_answer")
	Assessment_score = apps.get_model("systech_account", "Assessment_score")

	Company_assessment.objects.filter(consultant=215).update(credits_left = F("session_credits"))
	Assessment_session.objects.filter(company_assessment__consultant=215).delete()
	Assessment_upload_answer.objects.filter(company_assessment__consultant=215).delete()
	Assessment_score.objects.filter(company_assessment__consultant=215).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0023_auto_20180405_1821'),
    ]

    operations = [
    	migrations.RunPython(delete_data)
    ]
