# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-16 06:52
from __future__ import unicode_literals

from django.db import migrations


def migrateHasFollowUp(apps, schema_editor):
	Question = apps.get_model("systech_account", "Assessment_question")
	questionsQs = Question.objects.all()

	for question in questionsQs:
		if Question.objects.filter(is_related=question.id).exists():
			question.has_follow_up = True
			question.save()



class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0024_assessment_question_has_follow_up'),
    ]

    operations = [
    	migrations.RunPython(migrateHasFollowUp)
    ]
