# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-20 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0025_auto_20171116_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='assessment_answer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
        migrations.AddField(
            model_name='assessment_effect',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
        migrations.AddField(
            model_name='assessment_finding',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
        migrations.AddField(
            model_name='assessment_question',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
        migrations.AddField(
            model_name='assessment_recommendation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
        migrations.AddField(
            model_name='choice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
        migrations.AddField(
            model_name='generated_assessment_recommendation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
        migrations.AddField(
            model_name='transaction_type',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
        migrations.AddField(
            model_name='user_type',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
        migrations.AlterField(
            model_name='company_assessment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
    ]
