# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0026_auto_20171120_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display_setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_assessments', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_types', models.CharField(blank=True, max_length=200, null=True)),
                ('questions', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company')),
            ],
            options={
                'db_table': 'display_settings',
            },
        ),
    ]
