# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-22 06:44
from __future__ import unicode_literals

from django.db import migrations

def set_image_order(apps,schema_editor):
	Assessment_question = apps.get_model("systech_account", "Assessment_question")
	Assessment_image = apps.get_model("systech_account", "Assessment_image")

	assessment_questions = Assessment_question.objects.filter(is_active=True,uploaded_question=True)
	for assessment_question in assessment_questions:
		assessment_images = Assessment_image.objects.filter(is_active=True,question=assessment_question.pk).order_by("id")
		for idx, assessment_image in enumerate(assessment_images):
			assessment_image.order = idx + 1
			assessment_image.save()

class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0026_assessment_image_order'),
    ]

    operations = [
    	migrations.RunPython(set_image_order)
    ]
