# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-04 02:35
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0027_auto_20180522_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_answer',
            name='document_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=b'assessment/document_images/'),
        ),
    ]
