# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-04 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0028_auto_20180604_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_answer_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=b'assessment/document_images/')),
                ('item_no', models.IntegerField(blank=True, null=True)),
                ('company_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company_assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Assessment_question')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Transaction_type')),
            ],
            options={
                'db_table': 'assessment_answer_images',
            },
        ),
    ]
