# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-23 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0028_assessment_question_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_answer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment_answer',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
    ]
