# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-04 10:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0030_auto_20171128_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Related_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_questions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name=b'Assessment_question'), blank=True, null=True, size=None)),
                ('is_active', models.BooleanField(default=1)),
                ('is_import', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'related_questions',
            },
        ),
        migrations.RenameField(
            model_name='assessment_question',
            old_name='is_related',
            new_name='parent_question',
        ),
        migrations.AddField(
            model_name='assessment_question',
            name='has_related',
            field=models.BooleanField(default=0),
        ),
    ]
