# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-06 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0030_assessment_answer_image_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_dos_topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company')),
            ],
            options={
                'db_table': 'to_dos_topics',
            },
        ),
    ]
