# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-04 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0031_auto_20171204_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_type',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
