# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-06 05:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0031_to_dos_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_lesson_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('lesson', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('to_dos_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.To_dos_topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_lesson_updates',
            },
        ),
    ]
