# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-18 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0032_user_lesson_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_answer_image',
            name='is_sync',
            field=models.BooleanField(default=1),
        ),
    ]
