# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-05 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0032_transaction_type_transaction_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_related_required',
            new_name='follow_up_required',
        ),
        migrations.AddField(
            model_name='choice',
            name='required_document_image',
            field=models.BooleanField(default=0),
        ),
    ]
