# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-05 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0033_auto_20171205_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_type',
            name='exercise_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction_type',
            name='set_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction_type',
            name='total_items',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
