# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-28 05:59
from __future__ import unicode_literals

from django.db import migrations

def delete_duplicate_user_credit(apps,schema_editor):
	User_credit = apps.get_model("systech_account", "User_credit")

	User_credit.objects.filter(enrollment_id=1285).first().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0034_auto_20180621_1625'),
    ]

    operations = [
    	migrations.RunPython(delete_duplicate_user_credit)
    ]
