# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-05 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0034_auto_20171205_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_type',
            name='is_intelex',
            field=models.BooleanField(default=0),
        ),
    ]
