# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 02:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0035_transaction_type_is_intelex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_rename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('transaction_type', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name=b'Transaction_type'), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'company_rename',
            },
        ),
        migrations.AddField(
            model_name='display_setting',
            name='company_rename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
