# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0036_auto_20171206_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_rename',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
    ]
