# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0037_company_rename_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_assessment',
            name='company_rename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company_rename'),
        ),
        migrations.AlterField(
            model_name='company_assessment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company'),
        ),
    ]
