# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0039_related_question_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company')),
                ('company_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company_assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Assessment_question')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Transaction_type')),
            ],
            options={
                'db_table': 'assessment_scores',
            },
        ),
    ]
