# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0040_assessment_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment_score',
            name='company',
        ),
    ]
