# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0042_remove_assessment_score_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_score',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
