# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0043_assessment_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_intelex_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
