# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0044_user_user_intelex_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('company_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systech_account.Company_assessment')),
            ],
            options={
                'db_table': 'assessment_sessions',
            },
        ),
    ]
