# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 03:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0045_assessment_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.IntegerField(blank=True, null=True)),
                ('session_credits', models.DurationField(blank=True, null=True)),
                ('session_end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_credits',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='session_credits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='session_end_date',
        ),
        migrations.AddField(
            model_name='user_credit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
