# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0047_transaction_type_program_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_rename',
            name='is_intelex',
            field=models.BooleanField(default=0),
        ),
    ]
