# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0048_company_rename_is_intelex'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_rename',
            name='program_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
