# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0050_user_credit_program_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_credit',
            name='session_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
