# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-13 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0051_user_credit_session_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_assessment',
            name='session_credits',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
