# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-14 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0052_company_assessment_session_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_assessment',
            name='credits_left',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
