# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-15 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0053_company_assessment_credits_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_session',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
    ]
