# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systech_account', '0054_assessment_session_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_credit',
            name='session_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_credit',
            name='session_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
