from web_admin.models.crud import *
from web_admin.models.assessments import *
from web_admin.models.multiple_choice import *
from web_admin.models.company import *
from web_admin.models.company_assessment import *
from web_admin.models.user import *
from web_admin.models.settings import *
from web_admin.models.user_logs import *
from web_admin.models.enrollment import *
from web_admin.models.payment import *
from web_admin.models.session import *
from web_admin.models.timeslot import *
from web_admin.models.common_model import *
from web_admin.models.subject import *
from web_admin.models.question import *
from web_admin.models.student_answer import *
from web_admin.models.program import *
from web_admin.models.exercise import *
from web_admin.models.course import *
