# Generated by Django 2.1 on 2019-03-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='reference_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
