# Generated by Django 2.1 on 2019-03-13 03:01

from django.db import migrations


def generate_ref_no(apps, schema_editor):

    Enrollment = apps.get_model("web_admin", "Enrollment")

    enrollments = Enrollment.objects.all()

    for counter, enrollment in enumerate(enrollments):
        print(counter)
        print(enrollment.code)
        enrollment.reference_no = counter
        enrollment.save()

    # x = "str" + 1


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0002_enrollment_reference_no'),
    ]

    operations = [
        migrations.RunPython(generate_ref_no)
    ]
