# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-02 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0003_user_credit_session_credits_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_credit',
            name='enrollment_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
