# Generated by Django 2.1 on 2019-03-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0003_auto_20190313_1101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'company')},
        ),
    ]
