# Generated by Django 2.1 on 2019-03-14 12:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0005_exercisequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_edited', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.Company')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.AddField(
            model_name='studentsession',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='web_admin.Company'),
        ),
    ]
