# Generated by Django 2.1 on 2019-03-14 13:23

from django.db import migrations


def generate_ref_no(apps, schema_editor):

    Question = apps.get_model("web_admin", "Question")
    Company = apps.get_model("web_admin", "Company")

    company   = Company.objects.get(id=2)
    questions = Question.objects.all()

    for counter, question in enumerate(questions):
        print(counter)
        print(question.code)

        question.company = company
        question.save()


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0006_auto_20190314_2026'),
    ]

    operations = [
        migrations.RunPython(generate_ref_no)
    ]
