# Generated by Django 2.1 on 2019-03-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0008_auto_20190320_1411'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentsessionexercise',
            table='student_session_exercise',
        ),
    ]
