# Generated by Django 2.1 on 2019-03-20 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0010_sessionexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_edited', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.Company')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.Program')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.Session')),
            ],
            options={
                'db_table': 'program_sessions',
            },
        ),
    ]
