# Generated by Django 2.1 on 2019-03-26 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0013_enrollment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='exercise',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='exercise_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.ExerciseQuestion'),
        ),
    ]
