# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-13 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0014_trainernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexercise',
            name='trainer_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.TrainerNote'),
        ),
    ]
