# Generated by Django 2.1 on 2019-04-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0014_auto_20190326_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='session_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.SessionExercise'),
        ),
    ]
