# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-11 03:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0015_sessionexercise_trainer_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(blank=True, default=None, null=True)),
                ('time_end', models.TimeField(blank=True, default=None, null=True)),
                ('has_sunday', models.BooleanField(default=False)),
                ('has_monday', models.BooleanField(default=False)),
                ('has_tuesday', models.BooleanField(default=False)),
                ('has_wednesday', models.BooleanField(default=False)),
                ('has_thursday', models.BooleanField(default=False)),
                ('has_friday', models.BooleanField(default=False)),
                ('has_saturday', models.BooleanField(default=False)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'timeslots',
            },
        ),
    ]
