# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-16 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0016_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
