# Generated by Django 2.1 on 2019-04-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0016_studentanswer_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courseprogram',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='programsession',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionchoices',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.TextField(),
        ),
    ]
