# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-16 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0017_timeslot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.TimeSlot'),
        ),
    ]
