# Generated by Django 2.1 on 2019-04-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0020_exercise_is_post_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_assessment_test',
            field=models.BooleanField(default=False),
        ),
    ]
