# Generated by Django 2.1 on 2019-04-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0021_exercise_is_assessment_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.Course'),
        ),
    ]
