# Generated by Django 2.1 on 2019-04-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0022_exercise_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
