# Generated by Django 2.1 on 2019-04-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0023_exercise_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='default_image',
            field=models.ImageField(blank=True, default='/media/default_inventory.jpg', null=True, upload_to=''),
        ),
    ]
