# Generated by Django 2.1 on 2019-04-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0024_question_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='default_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
