# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-27 09:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0028_question_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_edited', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.QuestionChoices')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.SessionExercise')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_answers',
            },
        ),
    ]
