# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-08 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0030_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_intelex',
            field=models.BooleanField(default=0),
        ),
    ]
