# Generated by Django 2.1 on 2019-03-11 09:28

import datetime
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0031_company_is_intelex'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.Company'),
        ),
        migrations.AddField(
            model_name='questionchoices',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.Company'),
        ),
        migrations.AddField(
            model_name='questiontype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.Company'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.Company'),
        ),
        migrations.AddField(
            model_name='subject',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.Company'),
        ),
        migrations.AlterField(
            model_name='assessment_answer',
            name='choice',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='Choice'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='assessment_answer',
            name='document_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='assessment/document_images/'),
        ),
        migrations.AlterField(
            model_name='assessment_answer_image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='assessment/document_images/'),
        ),
        migrations.AlterField(
            model_name='assessment_image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='assessment/questions/'),
        ),
        migrations.AlterField(
            model_name='assessment_question',
            name='transaction_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='Transaction_type'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='company_assessment',
            name='transaction_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='Transaction_type'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='company_rename',
            name='transaction_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='Transaction_type'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='generated_assessment_recommendation',
            name='recommendations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='Assessment_recommendation'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='related_question',
            name='related_questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='Assessment_question'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='session_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 11, 9, 28, 53, 11928, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
